project:
  type: website
  output-dir: docs

website:
  title: "Amanda Plocharski"
  page-footer: 
     left: "Copyright 2022, Amanda Plocharski" 
     right: 
       - icon: github
         href: https://github.com/
       - icon: twitter 
         href: https://twitter.com/
  navbar:
     left:
       - href: index.qmd
         text: Home
       - about.qmd
       - href: https://drive.google.com/file/d/16QJeVmRLP8Actj60REueGNkIPuw-1W2R/view?usp=sharing
         text: Resume
       - portfolio.qmd
       - analysis.qmd
       - academic_example.qmd
       - news_story.qmd
       - analysis_va.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true




