---
title: "Academic Writing Example"
author: "Amanda Plocharski"
format:
  html:
    self-contained: true
    code-fold: true
    code-tools: true
---

This paper is a final project that I turned in for my Media History class during the fall 2021 semester. For this project, our class was told to research our hometown paper and dive into its history and impact on our local community. Being from right outside of Philadelphia, I choose to write on The Philadelphia Inquirer. I also reached out to and interviewed a reporter on the news team to supplement the writing piece.

## An Inquiry into *The Philadelphia Inquirer*

In the everchanging city of Philadelphia, *The Philadelphia Inquirer* has been one of the only constants. Placed near the railroad tracks at Broad Street and Callowhill in Center City, this paper has faced immense change and challenges, but has stuck around to become one of the most well-known papers in the country. *The Inquirer* and its owners have evolved into a household name, and it has become a trusted source for both those inside and outside of the city limits. June 1, 1829 saw a sudden and hot summer in the former nation\'s capital, but it also saw the founding of what would soon become one of the oldest surviving daily newspapers in the United States[\[1\]](#_ftn1). Norvell and John R. Walker, dissatisfied with the fact that all other papers seemed to be loyal to the European class system, sought to publish a paper that was dedicated to Jeffersonian Democracy[\[2\]](#_ftn2). Their paper, originally named *The Pennsylvanian Inquirer*, was to stand in the interests of all the people. Norvell, former editor of the *Aurora & Gazette*, was quoted saying:\
\
\"In a free state, there should always be an inquirer asking on behalf of the people: \'Why was this done? Why is that necessary work not done? Why is that man put forward? Why is that lawproposed? Why? Why? Why?\'\"[\[3\]](#_ftn3)\

Norvell and Walker looked to create a media legend in a city that already housed seven other outlets: *The Democratic Press, The Morning Journal, The Daily Courier, The United States Gazette, The National Gazette & Literary Register, The American Daily Advertiser and* the *Aurora & Gazette[**\[4\]**](#_ftn4)*. Through various merges, however, *The Inquirer* can claim that it is the oldest daily newspaper in America, even though it was technically founded years after other papers[\[5\]](#_ftn5). *The
Pennsylvania Packet* has its first issue dating back to Monday, October 28,
1771, and through different owners and various sells, this paper became housed
under the same ownership as *The Inquirer[**\[6\]**](#_ftn6).* Through time, owners decided to merge papers and ended up with *The Inquirer* as the face of their ownership. \
The paper was under the ownership of Norvell and Walker for only six months when they sold it to Jesper Harding ---- associate editor of the *United States Gazette* and the leading publisher of the Bible in the country[\[7\]](#_ftn7). His goal was to create a publishing powerhouse ­­---- a seemingly impossible feat that soon proved to be possible. By 1842, only 13 years after becoming owner, Harding had bought four of the competing newspapers in the city and merged them with *The Inquirer*: *The Daily Journal, The Morning Journal, The Daily Courier, The National Gazette and The Literary Register[**\[8\]**](#_ftn8)*. The owner of *The* *Daily Courier*, James Gordon Bennett, would soon run off to New York and found the *New York Herald*. To keep up with the rising demand of news and the acquisition of more papers and readers, Harding built his own paper mill[\[9\]](#_ftn9). Under Harding, the paper also tried to stay true to its original political ties, but that feat was soon proven difficult. Their loyalty to the Democratic party shifted after President Andrew Jackson removed all funds from the Second Bank of the U.S. in 1833 ---- a bank located in the heart of Philadelphia. After that, the paper backed the anti-Jackson wing of the Democratic party[\[10\]](#_ftn10).

Following the retirement of Harding in 1860, his son, William Harding, fully took over *The Inquirer* after being a partner for a few years[\[11\]](#_ftn11). He brought immense changes to the paper within the first few years of ownership. Harding changed the paper\'s name from *The Pennsylvanian Inquirer* to *The Philadelphia Inquirer,* changed the circulation so that it went mostly to annual subscribers, cut the single-copy price from three cents to two cents and also established delivery routes for paper boys[\[12\]](#_ftn12). The paper was also one of the first in the nation to use a web fed rotary press, which allowed them to have printing on both sides of the paper[\[13\]](#_ftn13). Three years into his full ownership, the circulation for *The Inquirer*
had risen from 7,000 to 70,000.

Harding carried the paper through coverage in the Civil War, and the paper and its subsequent coverage proved to be huge during this time. Harding not only brought the news of the armies to readers, but he also sent *The Inquirer* to the armies[\[14\]](#_ftn14). When the government sought to tell their troops about new steps in the war, it asked *The Inquirer* to issue a special edition for its armies. Both sides of the war also read *The Inquirer* because they thought it and its reporters were the most objective[\[15\]](#_ftn15). The war also brought about one of the nation\'s all-time greatest battlefield journalists, Uriah Hunt Painter, who worked for *The Inquirer*. Painter was the one who correctly reported the Confederate win in the first Battle of Bull Run when other outlets falsely claimed a Union victory[\[16\]](#_ftn16). He became known to generals and other government officials and traveled across the country at the drop of a hat to report[\[17\]](#_ftn17).

Harding held ownership of the paper until 1889 when it was sold to British-born James Elverson[\[18\]](#_ftn18). At this point in time, *The Inquirer* was just a memory of what it once was. Their reporting on the Civil War was a peak, but soon after the war ended their circulation dropped. Elverson purchased the paper with the intention of restoring an institution that he had admired, and he began by moving the paper into a new building with the most advanced printing resources[\[19\]](#_ftn19). Elverson was also the first publisher to run his entire pressroom by electricity. In 1889, he created a Sunday edition of the paper as well.

After Elverson died, the paper was handed down to his son, James Elverson Jr. Under his ownership, *The Inquirer* increased its \"political clout\" in the very Republican commonwealth. The paper soon became known as the \"Republican Bible of Pennsylvania\"[\[20\]](#_ftn20). This was the time when *The Inquirer* was looking to keep pace with the so-called mechanical age. It began using motor trucks to transport its paper and started to implement color printing[\[21\]](#_ftn21). Elverson Jr. was also the editor to build and move the newspaper into the building that it currently resides in, and this building was heralded as the most modern and fully equipped newspaper plant in the world[\[22\]](#_ftn22).  Elverson Jr. died of a heart attack in *The Inquirer* building in 1929, and it took the paper seven years to find a fully defined owner after his death[\[23\]](#_ftn23).

The paper went through many owners before being bought by M.L. Annenberg for \$12 million in 1936[\[24\]](#_ftn24). He was considered the first \"well-known\" boss after the seven years of iffy ownership. Under Annenberg, circulation climbed immensely. The daily circulation had risen to 345,422 and its Sunday circulation rose to 1,035,871 after only two years[\[25\]](#_ftn25). Annenberg, however, was soon charged with tax evasion and sent to prison. He maintained ownership until he died in 1942[\[26\]](#_ftn26). Walter Annenberg, his son, quickly took over. Under him, *The Inquirer* became the sole morning publication in the city, and they announced that they were becoming an editorially independent newspaper rather than a GOP-oriented one[\[27\]](#_ftn27). In 1951, they backed the Democratic candidates in the election for Philadelphia\'s new mayor. Today, the newspaper is considered to have more of a left-leaning slant, but just slightly. In 1969, President Richard Nixon appointed Annenberg to be the Ambassador to Britain, so he decided to sell the paper to Knight Newspapers Inc.[\[28\]](#_ftn28). They held ownership until 2014 when philanthropist H.F. \"Gerry\" Lenfest purchased *The Inquirer* and donated it to the Lenfest Institute for Journalism[\[29\]](#_ftn29). It is now the largest newspaper in the United States that operates as a public-benefit corporation.

Justine McDaniel flew across the country seven years ago to begin her job at *The Inquirer.* As a California native, McDaniel saw the six-hour flight and cross-country relocation as nothing but an opportunity to start her dream job. She began her work as a suburban bureau reporter until quickly moving onto the policy team where she looked at different state policies in different areas. A few years after her hiring, she became a general assignment reporter where she covered a much wider range of topics. When the pandemic hit, she was one of the first people tapped to start working on the COVID-19 beat. Her first story came out in early January, right before it had arrived in the United States, and she has
been working on it since.

McDaniel acknowledged the dense history of Philadelphia as a city itself, but also of the paper.

\"I do think there's such a strong Philadelphia culture. And, like, *The Inquirer*, you know, its history is part of that,\" she said. \"So, I guess just learning about all of that, for me has been interesting and becoming part of that. And, you know, my work definitely helps make me feel part of that.\"

McDaniel emphasized that the paper is so engrained into the community and also in the history of the city. There is importance, she said, in startups and smaller newspapers, but it is also important to keep papers alive, especially ones with an immense history.

\"I do feel really lucky to work somewhere where the name is so established in the community,\" she said. \"And everyone knows *The Inquirer* and you know, it means that people understand what you're doing a lot of the time when you reach out to them or whatever. So, I feel really lucky to work somewhere with so much, you know, weight behind it.\"

With this established name and such rich history, McDaniel acknowledges that it makes her job easier to do. The trust that people have placed over the years into this institution makes them more willing to talk and more willing to be honest. If they trust the paper, they will trust that they will report the right way. In being around for so long it has created an open area of trust and importance in the community.

\"There's definitely always a sense that I want to do right by the paper, because the paper is so important to me,\" she said. \"It's such a big, wonderful place with all its history.\"

In being around for so long though, the paper has also had to deal with an immensely changing industry. From printing on only one side of the paper to going digital, almost 200 years of history means that this paper has had to adapt to a lot. In just her seven years of working with *The Inquirer*, McDaniel has even seen drastic changes to the website. The paper has changed the way it reaches its audience and also how it presents it content, and the way they write their headlines has even changed.

\"So, all of that kind of stuff, it's in the forefront of everyone's mind all the time. I think or at least mine, you know, when I'm working,\" McDaniel said. \"It's just kind of baked into what we do now. Rather than, you know, maybe in previous decades, it was more of like you have to think harder about it, maybe more of an afterthought. The situation was just so different.\"

Adaption has taken place throughout its history by previous owners, by moving them into new state-of-the-art buildings or beginning to run their newsroom on full electricity, but there has been more adaptation done recently as well. The donation of *The Inquirer* to the Lenfest Institute placed both the paper and Philadelphia itself at the epicenter of a national effort to protect and transform local news in the digital age. They have also adapted to the financial hardships of keeping a paper running, as the Institute\'s work with *The Inquirer* is entirely supported by private philanthropy[\[30\]](#_ftn30).

Adaptations within the paper not only came with just technological advances, but it also came in response to the increase in attention on social issues. When covering the Black Lives Matter protests in response to the murder of George Floyd, *Inquirer* reporter Inga Saffron wrote a column titled \"Buildings Matter, Too\" ---- an apparent play on the BLM slogan[\[31\]](#_ftn31). There was outrage among both consumers and journalists within the newsroom and top editor at the time, Stan Wischnowski, stepped down soon after[\[32\]](#_ftn32). In response to this controversy, the paper has had to work on the inherent biases that come with a paper that has been around for so long and change the way they think of reporting. \"*Inquirer* for All\" was launched in response to the headline, and they have created resources, guides and tracking systems to attempt to make their work more accountable to Black, Indigenous and POC communities and journalists[\[33\]](#_ftn33). An Anti-Racist Workflow Guide was also created, and it offers a series of questions for reporters, editors and producers to consider at different points in the journalistic process. In the newsroom now, 61 percent of all newsroom positions were filled by individuals from BIPOC communities and 44 percent identified as women[\[34\]](#_ftn34). 

As a current 16-year resident of Pennsylvania, Lauren Plocharski has become a consistent reader of *The Inquirer*. The print edition used to be brought into her office and left in the break room, and that is when she would catch up on the news for the day.

\"It was an easy way to get my news, and I think once I started reading *The Inquirer*, it became one of the local news outlets I read consistently,\" she said. \"Besides the very local paper, it was one of the only newspapers that people ever read, or even brought into the office.\"

Plocharski had been a long-time resident of New Jersey before moving to a Philadelphia suburb in 2005 with her husband and two daughters. Before moving, she had read local Jersey papers and sometimes papers in New York. She still read their online versions, but it was easy to find a new paper to trust when making the move.

\"Everyone knows *The Inquirer*, some people back in New Jersey even read it,\" she said. \"They also had some reporting on New Jersey news, so it gave a sense of that old part of my life too.\"

Now, Plocharski finds herself clicking through their website almost daily while at work and home. For her more local news she reads the *Doylestown Patch*, which is based in her suburb, but she finds that *The Inquirer* has more in-depth and broad reporting ---- most likely due to more expansive resources. Sometimes these city-based papers can get lost in the new journalism world that is filled with
mega-outlets like FOX, CNN, AP and more, but to Plocharski, it is nice to see a
paper survive for so long.\

*The Inquirer* has been the recipient of multiple awards and has produced both noteworthy stories and journalists. Under Harding, they covered the Mexican War, supported Millard Fillmore in his election and also advocated for the election of President Abraham Lincoln. Many of Charles Dickens\' novels, including *Barnaby Rudge* and *Master Humphrey\'s Clock*, were also published for the first time in
America under *The Inquirer*\'s name[\[35\]](#_ftn35). Samuel Clemens, also better known as Mark Twain, was even a compositor in *The Inquirer*\'s back shop for a few months in the early 1850s[\[36\]](#_ftn36). Edgar Allen Poe\'s \"The Raven\" was also published in the paper on February 15,1845, as he was a resident of Philadelphia[\[37\]](#_ftn37). In 1894, *The Inquirer* advocated for the paving of Broad Street. It soon happened, and it became one of the \"world\'s finest boulevards\"[\[38\]](#_ftn38). The paper also advocated for the return of a sailor to U.S. grounds so that he could be honored for his service. He was soon returned, and his coffin was placed beneath the Liberty Bell where he laid in state for 24 hours. This is said to be the nation\'s first tribute on such a scale to an enlisted man[\[39\]](#_ftn39).\

During World War II, *The Inquirer* was represented in the fields by one of the war\'s most distinguished correspondents, Ivan H. \"Cy\" Peterman[\[40\]](#_ftn40). He walked with Allied forces through France and Germany and covered the early meetings on the United Nations when it was first formed. He had continual contact with generals and leaders of the UN made him a force to be reckoned with ---- but it also game him an ego[\[41\]](#_ftn41). When he was asked to return to Philadelphia and go back to his sports column, he \"balked\" and left the paper[\[42\]](#_ftn42).\

In 1979, The Three Mile Island nuclear reactor near Middletown, Pennsylvania partially melted down after there was a failure in one of the plant\'s sections. Eighty *Inquire* reporters, editors and photographers were put on the story, and they produced a 20,000-word account in five days that ran nine full pages in the Sunday paper[\[43\]](#_ftn43). This reporting won them a Pulitzer prize for local reporting. This story, however, was only one of 17 Pulitzers the paper won between the years of 1975 and 1990[\[44\]](#_ftn44). Since then, they have won three more, bringing their total to 20[\[45\]](#_ftn45).\

Their award-winning is not just limited to Pulitzer\'s though, as *The
Inquirer* has won more national journalism awards than any other newspaper
in the country. Other awards include the Roy W. Howard Award, the Ernie Pyle
Memorial Award, the University of Missouri Medal, the Robert Kennedy Award for
Photojournalism, the National Headliners Award, the Thomas L. Stokes Award, the
George Polk Award, the Heywood Broun Award, the George Loeb Award and numerous awards in different categories from the Society of Profession Journalists[\[46\]](#_ftn46).\

Through its rich and vast history, *The Inquirer* has proven itself to be a prominent and important institution. It has adapted to the changing journalism industry and is working to better itself in the changing climate. In its almost 200 years of existence, this paper has covered major events through U.S. History and has been a constant for the community members of Philadelphia and its surrounding suburbs. *The Inquirer* is an example of where good and trustworthy reporting can take a paper, and its leadership and drive has allowed it to thrive to the present time.  
\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_

Citations:

[\[1\]](#_ftnref1) Williams, Edgar. \"A history of The Inquirer,\"
Philly.com, June 20, 2003. DOA 12/10/2021
https://web.archive.org/web/20070219044935/http://www.philly.com/mld/inquirer/news/local/6135296.htm?1c

[\[2\]](#_ftnref2) ibid

[\[3\]](#_ftnref3) ibid

[\[4\]](#_ftnref4) Williams, Edgar. \"A history of The Inquirer,\" Philly.com,
June 20, 2003. DOA 12/10/2021
https://web.archive.org/web/20070219044935/http://www.philly.com/mld/inquirer/news/local/6135296.htm?1c

[\[5\]](#_ftnref5) Wilkinson, Gerry. \"The History of the Philadelphia
Inquirer,\" The Philadelphia Press Association. DOA 12/10/2021
http://www.phillyppa.com/inquirer.html

[\[6\]](#_ftnref6) ibid

[\[7\]](#_ftnref7) Williams, Edgar. \"A history of The Inquirer,\"
Philly.com, June 20, 2003. DOA 12/10/2021
https://web.archive.org/web/20070219044935/http://www.philly.com/mld/inquirer/news/local/6135296.htm?1c

[\[8\]](#_ftnref8) Williams, Edgar. \"A history of The Inquirer,\"
Philly.com, June 20, 2003. DOA 12/10/2021
https://web.archive.org/web/20070219044935/http://www.philly.com/mld/inquirer/news/local/6135296.htm?1c

[\[9\]](#_ftnref9) ibid

[\[10\]](#_ftnref10) Williams, Edgar. \"A history of The Inquirer,\"
Philly.com, June 20, 2003. DOA 12/10/2021
https://web.archive.org/web/20070219044935/http://www.philly.com/mld/inquirer/news/local/6135296.htm?1c

[\[11\]](#_ftnref11) ibid

[\[12\]](#_ftnref12) ibid

[\[13\]](#_ftnref13) Wilkinson, Gerry. \"The History of the Philadelphia
Inquirer,\" The Philadelphia Press Association. DOA 12/10/2021 http://www.phillyppa.com/inquirer.html

[\[14\]](#_ftnref14) Williams, Edgar. \"A history of The Inquirer,\"
Philly.com, June 20, 2003. DOA 12/10/2021
https://web.archive.org/web/20070219044935/http://www.philly.com/mld/inquirer/news/local/6135296.htm?1c

[\[15\]](#_ftnref15) ibid

[\[16\]](#_ftnref16) Williams, Edgar. \"A history of The Inquirer,\"
Philly.com, June 20, 2003. DOA 12/10/2021
https://web.archive.org/web/20070219044935/http://www.philly.com/mld/inquirer/news/local/6135296.htm?1c

[\[17\]](#_ftnref17) Williams, Edgar. \"A history of The Inquirer,\" Philly.com,
June 20, 2003. DOA 12/10/2021
https://web.archive.org/web/20070219044935/http://www.philly.com/mld/inquirer/news/local/6135296.htm?1c

[\[18\]](#_ftnref18) ibid

[\[19\]](#_ftnref19) ibid

[\[20\]](#_ftnref20) Williams, Edgar. \"A history of The Inquirer,\"
Philly.com, June 20, 2003. DOA 12/10/2021 https://web.archive.org/web/20070219044935/http://www.philly.com/mld/inquirer/news/local/6135296.htm?1c

[\[21\]](#_ftnref21) ibid

[\[22\]](#_ftnref22) Wilkinson, Gerry. \"The History of the Philadelphia
Inquirer,\" The Philadelphia Press Association. DOA 12/10/2021
http://www.phillyppa.com/inquirer.html

[\[23\]](#_ftnref23) Williams, Edgar. \"A history of The Inquirer,\"
Philly.com, June 20, 2003. DOA 12/10/2021
https://web.archive.org/web/20070219044935/http://www.philly.com/mld/inquirer/news/local/6135296.htm?1c

[\[24\]](#_ftnref24) Wilkinson, Gerry. \"The History of the Philadelphia
Inquirer,\" The Philadelphia Press Association. DOA 12/10/2021
http://www.phillyppa.com/inquirer.html

[\[25\]](#_ftnref25) Williams, Edgar. \"A history of The Inquirer,\"
Philly.com, June 20, 2003. DOA 12/10/2021
https://web.archive.org/web/20070219044935/http://www.philly.com/mld/inquirer/news/local/6135296.htm?1c

[\[26\]](#_ftnref26) ibid

[\[27\]](#_ftnref27) ibid

[\[28\]](#_ftnref28) Wilkinson, Gerry. \"The History of the Philadelphia
Inquirer,\" The Philadelphia Press Association. DOA 12/10/2021
http://www.phillyppa.com/inquirer.html

[\[29\]](#_ftnref29) \"The Philadelphia Inquirer,\" The Lenfest Institute.
DOA 12/11/2021 https://www.lenfestinstitute.org/inquirer-support/

[\[30\]](#_ftnref30) \"The Philadelphia Inquirer,\" The Lenfest Institute.
DOA 12/11/2021 https://www.lenfestinstitute.org/inquirer-support/

[\[31\]](#_ftnref31) Wenzel, Andrea. \"The Philadelphia Inquirer is working
to transform its newsroom. Here\'s what it\'s done in a year,\" Poynter, August
27, 2021. DOA 12/10/2021
https://www.poynter.org/reporting-editing/2021/the-philadelphia-inquirer-is-working-to-transform-its-newsroom-heres-what-its-done-in-a-year/

[\[32\]](#_ftnref32) Tracy, Marc. \"Top Editor of Philadelphia Inquirer
Resigns After \'Buildings Matter\' Headline,\" The New York Times, June 6, 2020.
DOA 12/11/2021
https://www.nytimes.com/2020/06/06/business/media/editor-philadephia-inquirer-resigns.html

[\[33\]](#_ftnref33) Wenzel, Andrea. \"The Philadelphia Inquirer is
working to transform its newsroom. Here\'s what it\'s done in a year,\" Poynter,
August 27, 2021. DOA 12/10/2021
https://www.poynter.org/reporting-editing/2021/the-philadelphia-inquirer-is-working-to-transform-its-newsroom-heres-what-its-done-in-a-year/

[\[34\]](#_ftnref34) ibid

[\[35\]](#_ftnref35) Williams, Edgar. \"A history of The Inquirer,\"
Philly.com, June 20, 2003. DOA 12/10/2021
https://web.archive.org/web/20070219044935/http://www.philly.com/mld/inquirer/news/local/6135296.htm?1c

[\[36\]](#_ftnref36) Williams, Edgar. \"A history of The Inquirer,\"
Philly.com, June 20, 2003. DOA 12/10/2021
https://web.archive.org/web/20070219044935/http://www.philly.com/mld/inquirer/news/local/6135296.htm?1c

[\[37\]](#_ftnref37) Wilkinson, Gerry. \"The History of the Philadelphia
Inquirer,\" The Philadelphia Press Association. DOA 12/10/2021
http://www.phillyppa.com/inquirer.html

[\[38\]](#_ftnref38) Williams, Edgar. \"A history of The Inquirer,\"
Philly.com, June 20, 2003. DOA 12/10/2021 https://web.archive.org/web/20070219044935/http://www.philly.com/mld/inquirer/news/local/6135296.htm?1c

[\[39\]](#_ftnref39) ibid

[\[40\]](#_ftnref40) ibid

[\[41\]](#_ftnref41) ibid

[\[42\]](#_ftnref42) ibid

[\[43\]](#_ftnref43) ibid

[\[44\]](#_ftnref44) Williams, Edgar. \"A history of The Inquirer,\"
Philly.com, June 20, 2003. DOA 12/10/2021 https://web.archive.org/web/20070219044935/http://www.philly.com/mld/inquirer/news/local/6135296.htm?1c

[\[45\]](#_ftnref45) \"The Philadelphia Inquirer,\" Wikipedia. DOA
12/11/2021 https://en.wikipedia.org/wiki/The_Philadelphia_Inquirer

[\[46\]](#_ftnref46) Williams, Edgar. \"A history of The Inquirer,\"
Philly.com, June 20, 2003. DOA 12/10/2021
https://web.archive.org/web/20070219044935/http://www.philly.com/mld/inquirer/news/local/6135296.htm?1c
