---
title: "Portfolio"
---

Hi there, this is my portfolio page!

## The spirits of The Hatchet townhouse

This is a video I produced for The Hatchet's annual Halloween Guide where we brought a psychic/medium into our newspaper's townhouse to see if he could communicate with any spirits living within our walls.

[Watch this video on YouTube here](https://www.youtube.com/watch?v=ukJiyXG6t58&t=1s)


## Student discusses living on campus this fall

This video highlights the type of work that I was able to produce during the peak of the pandemic when being away from my campus, yet continuing to have to report on it. The GW Hatchet was also one of the only student newspapers that continued to produce content when students were sent home in the 2020 spring semester.

[Watch this video on YouTube here](https://www.youtube.com/watch?v=S9c6fvdxAQ0)


## Enchant Christmas Light Maze debuts in Nationals Park

Enchant Christmas invited our student newspaper to the opening of the "Enchant Christmas Light Maze" in late 2019. The maze and market welcomed more than 1,000 attendees in its first night and changes its theme each year to attract new guests and create different experiences. Enchant Christmas also published this video on their own website, and it has amassed almost 8K views. 

[Watch this video on YouTube here](https://www.youtube.com/watch?v=xSZ0TSWJTic&t=58s)
